spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080
avatarPath: /root/myFile/images/avatar
blogPicPath: /root/myFile/images/blog
remoteIP: 132.232.14.175
ftpUser: root
ftpPwd: iamperfact1